Add server response error message

diff --git a/claude-cli b/claude-cli
--- a/claude-cli
+++ b/claude-cli
@@ -12,10 +12,25 @@ if [ $# -ne 1 ]; then
 	exit 1
 fi
 
+JSON="$(mktemp)"
+
 curl https://api.anthropic.com/v1/messages \
 	--silent \
 	--header "x-api-key: $ANTHROPIC_API_KEY" \
 	--header "anthropic-version: 2023-06-01" \
 	--header "content-type: application/json" \
 	--data "$(jq -Rs '{ model: "claude-3-opus-20240229", max_tokens: 1024, messages: [ {role: "user", content: . } ] }' | sed -e "s/\"content\": \"/\"content\": \"$1: /")" \
-	| jq -r '.content[] | .text'
+	> "$JSON"
+
+if [ $? -ne 0 ]; then
+	rm "$JSON"
+	exit 1
+fi
+
+if ! cat $JSON | jq -r '.content[] | .text' 2> /dev/null; then
+	>&2 echo "Server terminated for the following reason: $(cat $JSON | jq -r '.error | .type' 2> /dev/null)"
+	rm "$JSON"
+	exit 1
+fi
+
+rm "$JSON"
