Update README.md and error messages

diff --git a/lt-llm-cli b/lt-llm-cli
--- a/lt-llm-cli
+++ b/lt-llm-cli
@@ -6,7 +6,6 @@ if [ $# -ne 2 ]; then
 	exit 1
 fi
 
-
 LT_CLI="$1"
 LT_PARAM="$2"
 
@@ -57,7 +56,7 @@ for i in $TEMPFILE*; do
 		retry $i
 	fi
 	if [ $? -ne 0 ]; then
-		>&2 echo "Failed to process a part of the input"
+		>&2 echo -e "\e[31mFailed to process a part of the input. This is an unrecoverable error.\e[0m"
 	fi
 
 	sleep $LT_SLEEP_SEC
